# Generated by Django 4.2.1 on 2023-06-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_user_comments_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='instance_type',
            field=models.CharField(blank=True, choices=[('post', 'post')], max_length=32, verbose_name='Instance type'),
        ),
    ]
