# Generated by Django 4.2.1 on 2023-06-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comments_instance_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comments',
            name='comments_co_content_0da227_idx',
        ),
    ]
