# Generated by Django 4.2.1 on 2023-06-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_remove_comments_comments_co_content_0da227_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['content_type', 'object_id'], name='comments_co_content_0da227_idx'),
        ),
    ]
