# Generated by Django 4.1.7 on 2023-03-27 23:26

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=mdeditor.fields.MDTextField(verbose_name='Text'),
        ),
    ]
