# Generated by Django 4.2 on 2023-04-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_token_expired'),
        ('posts', '0002_alter_posts_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts',
                                    to='users.userprofile', verbose_name='Creator of post'),
        ),
    ]
