# Generated by Django 4.2.1 on 2023-06-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='instance_type',
            field=models.CharField(blank=True, choices=[('post', 'post')], max_length=32, verbose_name='Instance type'),
        ),
    ]
