# Generated by Django 4.2.1 on 2023-06-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_likes_instance_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='user',
            new_name='creator',
        ),
    ]
