# Generated by Django 4.2.1 on 2023-06-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_rename_user_likes_creator'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='likes',
            index=models.Index(fields=['content_type', 'object_id'], name='likes_likes_content_e2cbe5_idx'),
        ),
    ]
