# Generated by Django 4.2.1 on 2023-06-05 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('followings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followingcategory',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='followingcategory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Following object model'),
        ),
    ]
