# Generated by Django 4.2.1 on 2023-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followings', '0002_remove_followingcategory_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followingcategory',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
