# Generated by Django 4.1.7 on 2023-03-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450, unique=True, verbose_name='Tag name')),
                ('description', models.TextField(max_length=2000, verbose_name='Tag description')),
                ('icon', models.ImageField(blank=True, upload_to='images/tags/', verbose_name='Tag icon')),
                ('slug', models.SlugField(unique=True, verbose_name='Tag slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
    ]
