# Generated by Django 4.1.7 on 2023-03-27 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_tagsubscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Tag slug'),
        ),
        migrations.AlterField(
            model_name='tagsubscribers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_subs', to=settings.AUTH_USER_MODEL, verbose_name='Subscriber'),
        ),
    ]
