# Generated by Django 4.1.7 on 2023-03-27 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0003_alter_tags_slug_alter_tagsubscribers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsubscribers',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_subs', to='tags.tags', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='tagsubscribers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subscriber'),
        ),
    ]
