# Generated by Django 4.2.1 on 2023-05-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
