# Generated by Django 4.2.1 on 2023-05-28 14:49

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='cover_photo',
            field=models.ImageField(upload_to=apps.posts.models.post_image_upload_path, verbose_name='Cover of post'),
        ),
    ]
