# Generated by Django 4.2.1 on 2023-05-24 21:18

import apps.users.services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/user', verbose_name='Avatar')),
                ('bio', models.CharField(blank=True, max_length=700, null=True, verbose_name='Bio')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('socials', models.JSONField(default=apps.users.services.social_media_json, verbose_name='Social media links')),
                ('settings', models.JSONField(default=apps.users.services.settings_json, verbose_name='Settings')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
