# Generated by Django 4.2.1 on 2023-05-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0006_alter_followingcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='followingcategory',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Following object'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followingcategory',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
