# Generated by Django 4.2.1 on 2023-05-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_followingcategory_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='following_category',
        ),
        migrations.AlterField(
            model_name='followingcategory',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
