# Generated by Django 4.2.1 on 2023-06-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followingcategory',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
        migrations.DeleteModel(
            name='FollowingCategory',
        ),
    ]
