# Generated by Django 4.1.7 on 2023-04-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('token', models.CharField(max_length=32, verbose_name='Token')),
                ('token_type', models.CharField(choices=[('su', 'Sign Up Token'), ('ce', 'Change email Token')], max_length=2, verbose_name='Token types')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
