# Generated by Django 4.1.7 on 2023-04-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
