# Generated by Django 4.1.7 on 2023-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='Token')),
                ('token_type', models.CharField(blank=True, choices=[('su', 'Sign Up Token'), ('ce', 'Change Email Token'), ('pr', 'Password Reset Token')], max_length=2, null=True, verbose_name='Type of token')),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Owner of token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Token creation date')),
                ('deletion_date', models.DateTimeField(blank=True, null=True, verbose_name='Token deletion date')),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
