# Generated by Django 4.1.7 on 2023-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='deletion_date',
            field=models.DateTimeField(blank=True, default=models.DateTimeField(auto_now_add=True, verbose_name='Token creation date'), null=True, verbose_name='Token deletion date'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='Token'),
        ),
    ]
