# Generated by Django 4.1.7 on 2023-04-05 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_token_deletion_date_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Token creation date'),
        ),
        migrations.AlterField(
            model_name='token',
            name='deletion_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 5, 17, 15, 26, 725731, tzinfo=datetime.timezone.utc), null=True, verbose_name='Token deletion date'),
        ),
    ]
