# Generated by Django 4.1.7 on 2023-04-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_token_created_alter_token_deletion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='deletion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Token deletion date'),
        ),
    ]
